"""add embedded_links to candidates

Revision ID: 0de67dea7283
Revises: ae92f5b8830e
Create Date: 2026-07-19 09:40:16.294939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0de67dea7283'
down_revision: Union[str, None] = 'ae92f5b8830e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
