"""add github_signal_score to candidates

Revision ID: 0e49ffa6f12a
Revises: 4e41d285f34b
Create Date: 2026-07-19 10:19:54.950660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e49ffa6f12a'
down_revision: Union[str, None] = '4e41d285f34b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('github_signal_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'github_signal_score')
    # ### end Alembic commands ###
