"""create match_scores table

Revision ID: 105ba7e5befb
Revises: f24742b76042
Create Date: 2026-07-18 14:21:05.211891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '105ba7e5befb'
down_revision: Union[str, None] = 'f24742b76042'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('breakdown', sa.Text(), nullable=True),
    sa.Column('matched_required_skills', sa.Text(), nullable=True),
    sa.Column('missing_required_skills', sa.Text(), nullable=True),
    sa.Column('matched_nice_to_have_skills', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_scores')
    # ### end Alembic commands ###
