"""add ai_feedback to match_scores

Revision ID: 1c56159cf835
Revises: 105ba7e5befb
Create Date: 2026-07-19 09:23:41.158484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c56159cf835'
down_revision: Union[str, None] = '105ba7e5befb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_scores', sa.Column('ai_feedback', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match_scores', 'ai_feedback')
    # ### end Alembic commands ###
