"""add embedded_links to candidates

Revision ID: 4e41d285f34b
Revises: 0de67dea7283
Create Date: 2026-07-19 09:47:55.969504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e41d285f34b'
down_revision: Union[str, None] = '0de67dea7283'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('embedded_links', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'embedded_links')
    # ### end Alembic commands ###
