"""add user_id to company_integrations

Revision ID: 72f75e21e817
Revises: 95e741a463f0
Create Date: 2026-07-21 10:43:09.183564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72f75e21e817'
down_revision: Union[str, None] = '95e741a463f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_integrations', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'company_integrations', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'company_integrations', type_='foreignkey')
    op.drop_column('company_integrations', 'user_id')
    # ### end Alembic commands ###
