"""add users table and user_id to jobs/candidates

Revision ID: 95e741a463f0
Revises: 7423fdb883f0
Create Date: 2026-07-20 19:29:56.436371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95e741a463f0'
down_revision: Union[str, None] = '7423fdb883f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('account_type', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.add_column('candidates', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'candidates', 'users', ['user_id'], ['id'])
    op.add_column('jobs', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'jobs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'user_id')
    op.drop_constraint(None, 'candidates', type_='foreignkey')
    op.drop_column('candidates', 'user_id')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
