"""add parsed_requirements to jobs

Revision ID: f24742b76042
Revises: b88d1ee2248e
Create Date: 2026-07-18 14:12:15.675728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f24742b76042'
down_revision: Union[str, None] = 'b88d1ee2248e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('parsed_requirements', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'parsed_requirements')
    # ### end Alembic commands ###
